# This playbook setup SEAPATH on a debian machine
# The machine must previously have been flashed
# with an iso created by build_debian_iso
#
---
- name: run debian prerequisites
  ansible.builtin.import_playbook: cluster_setup_prerequisdebian.yaml
- name: run cluster network setup
  ansible.builtin.import_playbook: cluster_setup_network.yaml

- name: copy and enable custom services
  hosts: all
  become: true
  tasks:

  - name: copy cache_allocator.service unit file
    ansible.builtin.copy:
      src: ../src/cache_allocator.service
      dest: /etc/systemd/system/cache_allocator.service
      owner: root
      group: root
      mode: '0644'

  - name: copy cache_allocator.sh
    ansible.builtin.copy:
      src: ../src/cache_allocator.sh
      dest: /usr/local/sbin/cache_allocator.sh
      owner: root
      group: root
      mode: '0754'

  - name: enable cache_allocator.service
    ansible.builtin.systemd_service:
      name: cache_allocator.service
      enabled: true

  - name: copy online_cpus.service unit file
    ansible.builtin.copy:
      src: ../src/online_cpus.service
      dest: /etc/systemd/system/online_cpus.service
      owner: root
      group: root
      mode: '0644'

  - name: copy online_cpus.sh
    ansible.builtin.copy:
      src: ../src/online_cpus.sh
      dest: /usr/local/sbin/online_cpus.sh
      owner: root
      group: root
      mode: '0754'

  - name: enable online_cpus.service
    ansible.builtin.systemd_service:
      name: online_cpus.service
      enabled: true

- name: Restart all hosts
  hosts:
    - standalone_machine
  become: true
  tasks:

    - name: Restart to configure Debian
      reboot:
      when:
        - skip_reboot_setup_debian is not defined or not skip_reboot_setup_debian

    - name: Wait for host to be online
      wait_for_connection:
